#!/usr/bin/env bash
#
# Atlassian CLI (acli) Installation Script (Linux Only)
#
# This script installs the official Atlassian CLI on Linux systems.
# Supports: x86_64 and ARM64 (aarch64) architectures only.
#
# Versioned download URLs follow the pattern:
#   https://acli.atlassian.com/linux/{VERSION}/acli_{VERSION}_linux_{arch}.tar.gz
# SHA256 checksums are sourced from the Homebrew tap (auto-generated by GoReleaser):
#   https://github.com/atlassian/homebrew-acli
#
# Changelog / hash tracking:
#   https://developer.atlassian.com/cloud/acli/changelog/
#
# Usage:
#   ./install.sh                # Check and install acli
#   ./install.sh --check        # Only check, don't install

set -euo pipefail

# ============================================================================
# LOAD COMMON LIBRARY
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common.sh
source "$SCRIPT_DIR/../common.sh"

# ============================================================================
# VERSION AND SHA256 CHECKSUMS
# ============================================================================
# Update ACLI_VERSION and both SHA256 hashes together when upgrading.
# Fetch current checksums from the Homebrew tap formula:
#   https://github.com/atlassian/homebrew-acli/blob/main/Formula/acli.rb
# renovate: datasource=github-tags depName=atlassian/homebrew-acli
ACLI_VERSION="1.3.18-stable"
AMD64_SHA256="4ad4badc481ac1eff452f531c405a20422eb57513cc898d2a1f8ea945d6c24f6"
ARM64_SHA256="ac71711da43649854689ad0f74e44f18b0da3fd0ee776ceb4307ae7eb1e5da85"

# ============================================================================
# CONFIGURATION
# ============================================================================

if [ -z "${INSTALL_DIR:-}" ]; then
    if [ -w "/usr/local/bin" ]; then
        INSTALL_DIR="/usr/local/bin"
    else
        INSTALL_DIR="$HOME/.local/bin"
    fi
fi

TMP_DIR="${TMP_DIR:-/tmp/acli-install}"

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

check_acli() {
    if ! command_exists acli; then
        log "acli is not installed"
        return 1
    fi
    local version
    version=$(acli --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+[^ ]*' | head -1 || echo "unknown")
    log "acli is installed (${version})"
    return 0
}

# ============================================================================
# ACLI INSTALLATION
# ============================================================================

install_acli() {
    local arch
    arch=$(detect_arch)

    verify_linux || return 1

    if ! command_exists sha256sum; then
        log "ERROR: sha256sum is required but not installed" >&2
        return 1
    fi
    if ! command_exists tar; then
        log "ERROR: tar is required but not installed" >&2
        return 1
    fi

    local download_url archive_name expected_sha256
    if [ "$arch" = "x86_64" ]; then
        archive_name="acli_${ACLI_VERSION}_linux_amd64.tar.gz"
        expected_sha256="$AMD64_SHA256"
    else
        archive_name="acli_${ACLI_VERSION}_linux_arm64.tar.gz"
        expected_sha256="$ARM64_SHA256"
    fi
    download_url="https://acli.atlassian.com/linux/${ACLI_VERSION}/${archive_name}"

    log "Downloading acli for Linux $arch..."
    log "  URL: $download_url"

    mkdir -p "$TMP_DIR"
    curl -fsSL "$download_url" -o "${TMP_DIR}/${archive_name}"

    log "Verifying SHA256 checksum..."
    echo "${expected_sha256}  ${TMP_DIR}/${archive_name}" | sha256sum -c - || {
        log "ERROR: Checksum mismatch — the downloaded archive does not match the pinned SHA256." >&2
        log "  Expected: ${expected_sha256}" >&2
        log "  Update ACLI_VERSION and checksums in install.sh from the Homebrew tap formula." >&2
        rm -rf "$TMP_DIR"
        return 1
    }
    log "✓ Hash verified"

    log "Extracting..."
    tar -xzf "${TMP_DIR}/${archive_name}" -C "$TMP_DIR"

    # Find the acli binary in the extracted contents
    local binary
    binary=$(find "$TMP_DIR" -type f -name "acli" | head -1)
    if [ -z "$binary" ]; then
        log "ERROR: Could not find acli binary in extracted archive" >&2
        rm -rf "$TMP_DIR"
        return 1
    fi

    chmod +x "$binary"

    log "Installing to: $INSTALL_DIR"
    mkdir -p "$INSTALL_DIR"
    mv "$binary" "$INSTALL_DIR/acli"
    rm -rf "$TMP_DIR"

    if check_acli; then
        log "✓ acli installed successfully"
        return 0
    else
        log "✗ acli installation verification failed" >&2
        return 1
    fi
}

# ============================================================================
# MAIN SCRIPT
# ============================================================================

main() {
    local check_only=false

    while [[ $# -gt 0 ]]; do
        case $1 in
            -c|--check)
                check_only=true
                shift
                ;;
            *)
                log "ERROR: Unknown option: $1" >&2
                log "Usage: $(basename "$0") [--check]" >&2
                exit 1
                ;;
        esac
    done

    mkdir -p "$INSTALL_DIR"
    warn_if_not_in_path "$INSTALL_DIR"

    if [ "$check_only" = true ]; then
        check_acli
        exit $?
    fi

    if ! check_acli; then
        echo ""
        log "Installing acli..."
        install_acli
    fi
}

main "$@"
